[package]
name = "hydro-solvers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hydro-types = { path = "../hydro-types" }
hydro-hydraulics = { path = "../hydro-hydraulics" }
hydro-terrain = { path = "../hydro-terrain" }
hydro-norms = { path = "../hydro-norms" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
petgraph = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
oracle = { path = "../tests/oracle" }
