//! Oracle-parity integration tests for hydro-hydraulics.
//!
//! Each test loads the committed `hydraulics_golden.json` fixture (474 vectors
//! generated by the Python `hydro_engine` oracle) and asserts EXACT parity
//! (max_relative ≤ 1e-9) between the Rust implementations and the golden values.
//!
//! TDD cycle: these tests were written BEFORE production code.  They all fail
//! at first compile and go GREEN only when the implementations are correct.

use oracle::hydraulics::load_hydraulics_golden;

// Helper: relative error between got and expected.
fn rel_err(got: f64, expected: f64) -> f64 {
    (got - expected).abs() / expected.abs().max(1e-30_f64)
}

const TOL: f64 = 1e-9;

// ── T-2.1: Darcy-Weisbach ────────────────────────────────────────────────────

/// Swamee-Jain friction factor — 72 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_1_friction_factor_parity_72_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.darcy_weisbach.len(),
        72,
        "expected exactly 72 DW friction-factor vectors"
    );

    for (i, row) in golden.darcy_weisbach.iter().enumerate() {
        let got = hydro_hydraulics::darcy_weisbach::friction_factor(
            row.reynolds,
            row.roughness_mm,
            row.diameter_m,
        );
        let err = rel_err(got, row.friction_factor);
        assert!(
            err <= TOL,
            "DW friction_factor row {i}: Re={} eps_mm={} d={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.reynolds, row.roughness_mm, row.diameter_m, got, row.friction_factor, err
        );
    }
}

/// Darcy-Weisbach head loss — 60 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_1_head_loss_dw_parity_60_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.head_loss_dw.len(),
        60,
        "expected exactly 60 DW head-loss vectors"
    );

    for (i, row) in golden.head_loss_dw.iter().enumerate() {
        let got = hydro_hydraulics::darcy_weisbach::head_loss_dw(
            row.velocity_m_s,
            row.diameter_m,
            row.length_m,
            row.roughness_mm,
        );
        let err = rel_err(got, row.head_loss_m);
        assert!(
            err <= TOL,
            "DW head_loss row {i}: v={} d={} l={} r={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.velocity_m_s, row.diameter_m, row.length_m, row.roughness_mm, got, row.head_loss_m, err
        );
    }
}

// ── T-2.2: Hazen-Williams ────────────────────────────────────────────────────

/// Hazen-Williams velocity and head loss — 144 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_2_hazen_williams_parity_144_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.hazen_williams.len(),
        144,
        "expected exactly 144 HW vectors"
    );

    for (i, row) in golden.hazen_williams.iter().enumerate() {
        let vel = hydro_hydraulics::hazen_williams::velocity(row.flow_m3s, row.diameter_m);
        let vel_err = rel_err(vel, row.velocity_m_s);
        assert!(
            vel_err <= TOL,
            "HW velocity row {i}: flow={} d={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.flow_m3s,
            row.diameter_m,
            vel,
            row.velocity_m_s,
            vel_err
        );

        let hl = hydro_hydraulics::hazen_williams::head_loss(
            row.flow_m3s,
            row.diameter_m,
            row.length_m,
            row.c,
        );
        let hl_err = rel_err(hl, row.head_loss_m);
        assert!(
            hl_err <= TOL,
            "HW head_loss row {i}: flow={} d={} l={} c={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.flow_m3s, row.diameter_m, row.length_m, row.c, hl, row.head_loss_m, hl_err
        );
    }
}

// ── T-2.3: Manning ───────────────────────────────────────────────────────────

/// Manning full-pipe velocity and capacity — 90 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_3_manning_full_pipe_parity_90_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.manning_full_pipe.len(),
        90,
        "expected exactly 90 Manning full-pipe vectors"
    );

    for (i, row) in golden.manning_full_pipe.iter().enumerate() {
        let vel = hydro_hydraulics::manning::full_flow_velocity(
            row.diameter_m,
            row.slope,
            row.roughness_n,
        );
        let vel_err = rel_err(vel, row.velocity_m_s);
        assert!(
            vel_err <= TOL,
            "Manning full-pipe velocity row {i}: d={} s={} n={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.diameter_m, row.slope, row.roughness_n, vel, row.velocity_m_s, vel_err
        );

        let cap = hydro_hydraulics::manning::full_flow_capacity(
            row.diameter_m,
            row.slope,
            row.roughness_n,
        );
        let cap_err = rel_err(cap, row.capacity_m3s);
        assert!(
            cap_err <= TOL,
            "Manning full-pipe capacity row {i}: d={} s={} n={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.diameter_m, row.slope, row.roughness_n, cap, row.capacity_m3s, cap_err
        );
    }
}

/// Manning partial-flow ratios — 11 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_3_manning_partial_flow_parity_11_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.manning_partial_flow.len(),
        11,
        "expected exactly 11 Manning partial-flow vectors"
    );

    for (i, row) in golden.manning_partial_flow.iter().enumerate() {
        let (area_ratio, radius_ratio, flow_ratio) =
            hydro_hydraulics::manning::partial_flow_ratio(row.y_over_d);

        let ar_err = rel_err(area_ratio, row.area_ratio);
        assert!(
            ar_err <= TOL,
            "Manning partial area_ratio row {i}: y_d={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.y_over_d, area_ratio, row.area_ratio, ar_err
        );

        let rr_err = rel_err(radius_ratio, row.radius_ratio);
        assert!(
            rr_err <= TOL,
            "Manning partial radius_ratio row {i}: y_d={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.y_over_d, radius_ratio, row.radius_ratio, rr_err
        );

        let fr_err = rel_err(flow_ratio, row.flow_ratio);
        assert!(
            fr_err <= TOL,
            "Manning partial flow_ratio row {i}: y_d={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.y_over_d, flow_ratio, row.flow_ratio, fr_err
        );
    }
}

/// Rectangular open-channel velocity and flow — 72 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_3_rectangular_channel_parity_72_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.rectangular_channel.len(),
        72,
        "expected exactly 72 open-channel vectors"
    );

    for (i, row) in golden.rectangular_channel.iter().enumerate() {
        let vel = hydro_hydraulics::open_channel::rectangular_channel_velocity(
            row.width_m,
            row.depth_m,
            row.slope,
            row.roughness_n,
        );
        let vel_err = rel_err(vel, row.velocity_m_s);
        assert!(
            vel_err <= TOL,
            "Rectangular channel velocity row {i}: w={} d={} s={} n={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.width_m, row.depth_m, row.slope, row.roughness_n, vel, row.velocity_m_s, vel_err
        );

        let flow = hydro_hydraulics::open_channel::rectangular_channel_flow(
            row.width_m,
            row.depth_m,
            row.slope,
            row.roughness_n,
        );
        let flow_err = rel_err(flow, row.flow_m3s);
        assert!(
            flow_err <= TOL,
            "Rectangular channel flow row {i}: w={} d={} s={} n={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.width_m, row.depth_m, row.slope, row.roughness_n, flow, row.flow_m3s, flow_err
        );
    }
}

// ── T-2.4: Pump curves ───────────────────────────────────────────────────────

/// Pump head-at-flow evaluation — 25 vectors, max_relative ≤ 1e-9.
#[test]
fn t2_4_pump_curves_parity_25_vectors() {
    let golden = load_hydraulics_golden();
    assert_eq!(
        golden.pump_curves.len(),
        25,
        "expected exactly 25 pump-curve vectors"
    );

    for (i, row) in golden.pump_curves.iter().enumerate() {
        let curve = hydro_hydraulics::pump_curves::make_curve(row.shutoff_head_m, row.q_bep_m3s);
        let got = hydro_hydraulics::pump_curves::head_at_flow(&curve, row.query_flow_m3s);
        let err = rel_err(got, row.expected_head_m);
        assert!(
            err <= TOL,
            "Pump curve row {i}: shutoff={} q_bep={} q={} → got={:.15e} expected={:.15e} rel_err={:.3e}",
            row.shutoff_head_m, row.q_bep_m3s, row.query_flow_m3s, got, row.expected_head_m, err
        );
    }
}
