//! Typed structs and loaders for the hydraulics golden fixture.
//!
//! The fixture `hydraulics_golden.json` is generated by
//! `tests/oracle/gen/generate_hydraulics.py` and committed to the repository.
//! It contains test vectors for all hydraulic functions that require
//! EXACT parity (abs ≤ 1e-9) with the Python `hydro_engine` oracle.

use serde::{Deserialize, Serialize};

use crate::{load_fixture, OracleError};

// ── Darcy-Weisbach ───────────────────────────────────────────────────────────

/// One test vector for the Darcy-Weisbach Swamee-Jain friction factor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DarcyWeisbachRow {
    /// Reynolds number (dimensionless).
    pub reynolds: f64,
    /// Absolute pipe roughness (mm).
    pub roughness_mm: f64,
    /// Pipe diameter (m).
    pub diameter_m: f64,
    /// Expected Darcy-Weisbach friction factor (dimensionless).
    pub friction_factor: f64,
}

/// One test vector for the Darcy-Weisbach head loss.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeadLossDwRow {
    /// Flow velocity (m/s).
    pub velocity_m_s: f64,
    /// Pipe diameter (m).
    pub diameter_m: f64,
    /// Pipe length (m).
    pub length_m: f64,
    /// Absolute roughness (mm).
    pub roughness_mm: f64,
    /// Expected head loss (m).
    pub head_loss_m: f64,
}

// ── Hazen-Williams ────────────────────────────────────────────────────────────

/// One test vector for the Hazen-Williams head loss and velocity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HazenWilliamsRow {
    /// Flow rate (m³/s).
    pub flow_m3s: f64,
    /// Pipe diameter (m).
    pub diameter_m: f64,
    /// Pipe length (m).
    pub length_m: f64,
    /// Hazen-Williams C coefficient.
    pub c: f64,
    /// Expected head loss (m).
    pub head_loss_m: f64,
    /// Expected velocity (m/s).
    pub velocity_m_s: f64,
}

// ── Manning ───────────────────────────────────────────────────────────────────

/// One test vector for Manning full-pipe velocity and capacity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManningFullPipeRow {
    /// Pipe diameter (m).
    pub diameter_m: f64,
    /// Pipe slope (m/m).
    pub slope: f64,
    /// Manning's n roughness coefficient.
    pub roughness_n: f64,
    /// Expected full-pipe velocity (m/s).
    pub velocity_m_s: f64,
    /// Expected full-pipe flow capacity (m³/s).
    pub capacity_m3s: f64,
}

/// One test vector for Manning partial-flow ratios.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManningPartialFlowRow {
    /// Depth-to-diameter ratio (0..1).
    pub y_over_d: f64,
    /// Expected area ratio (A_partial / A_full).
    pub area_ratio: f64,
    /// Expected radius ratio (R_partial / R_full).
    pub radius_ratio: f64,
    /// Expected flow ratio (Q_partial / Q_full).
    pub flow_ratio: f64,
}

// ── Open channel ──────────────────────────────────────────────────────────────

/// One test vector for rectangular open-channel flow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RectangularChannelRow {
    /// Channel width (m).
    pub width_m: f64,
    /// Flow depth (m).
    pub depth_m: f64,
    /// Bed slope (m/m).
    pub slope: f64,
    /// Manning's n.
    pub roughness_n: f64,
    /// Expected velocity (m/s).
    pub velocity_m_s: f64,
    /// Expected flow rate (m³/s).
    pub flow_m3s: f64,
}

// ── Pump curves ───────────────────────────────────────────────────────────────

/// One test vector for pump head-at-flow evaluation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PumpCurveRow {
    /// Shutoff head (m) — H at Q=0.
    pub shutoff_head_m: f64,
    /// Best-efficiency-point flow (m³/s).
    pub q_bep_m3s: f64,
    /// Query flow (m³/s).
    pub query_flow_m3s: f64,
    /// Expected head at query flow (m).
    pub expected_head_m: f64,
}

// ── Aggregate fixture ─────────────────────────────────────────────────────────

/// All hydraulics test vectors in a single golden fixture file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HydraulicsGolden {
    /// Darcy-Weisbach friction factor vectors.
    pub darcy_weisbach: Vec<DarcyWeisbachRow>,
    /// Darcy-Weisbach head loss vectors.
    pub head_loss_dw: Vec<HeadLossDwRow>,
    /// Hazen-Williams vectors.
    pub hazen_williams: Vec<HazenWilliamsRow>,
    /// Manning full-pipe vectors.
    pub manning_full_pipe: Vec<ManningFullPipeRow>,
    /// Manning partial-flow ratio vectors.
    pub manning_partial_flow: Vec<ManningPartialFlowRow>,
    /// Rectangular open-channel vectors.
    pub rectangular_channel: Vec<RectangularChannelRow>,
    /// Pump curve evaluation vectors.
    pub pump_curves: Vec<PumpCurveRow>,
}

/// Load the committed `hydraulics_golden.json` fixture.
///
/// # Panics
///
/// Panics in tests when the fixture is missing or malformed — the fixture
/// must be present and correct for the test suite to be valid.
pub fn load_hydraulics_golden() -> HydraulicsGolden {
    load_fixture::<HydraulicsGolden>("hydraulics_golden")
        .expect("hydraulics_golden.json must be present and valid; regenerate with tests/oracle/gen/generate_hydraulics.py")
}

/// Load the committed fixture as `Result` (non-panicking variant).
pub fn try_load_hydraulics_golden() -> Result<HydraulicsGolden, OracleError> {
    load_fixture::<HydraulicsGolden>("hydraulics_golden")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Smoke test: the committed fixture file loads without error and contains
    /// the minimum required number of test vectors (≥ 10 per section).
    #[test]
    fn hydraulics_golden_loads_and_has_minimum_vectors() {
        let golden = load_hydraulics_golden();

        assert!(
            golden.darcy_weisbach.len() >= 10,
            "expected ≥ 10 DW friction-factor vectors, got {}",
            golden.darcy_weisbach.len()
        );
        assert!(
            golden.head_loss_dw.len() >= 10,
            "expected ≥ 10 DW head-loss vectors, got {}",
            golden.head_loss_dw.len()
        );
        assert!(
            golden.hazen_williams.len() >= 10,
            "expected ≥ 10 HW vectors, got {}",
            golden.hazen_williams.len()
        );
        assert!(
            golden.manning_full_pipe.len() >= 10,
            "expected ≥ 10 Manning full-pipe vectors, got {}",
            golden.manning_full_pipe.len()
        );
        assert!(
            golden.manning_partial_flow.len() >= 10,
            "expected ≥ 10 Manning partial-flow vectors, got {}",
            golden.manning_partial_flow.len()
        );
        assert!(
            golden.rectangular_channel.len() >= 5,
            "expected ≥ 5 open-channel vectors, got {}",
            golden.rectangular_channel.len()
        );
        assert!(
            golden.pump_curves.len() >= 5,
            "expected ≥ 5 pump-curve vectors, got {}",
            golden.pump_curves.len()
        );
    }

    /// Schema smoke test: each DW row has physically plausible values.
    #[test]
    fn darcy_weisbach_rows_are_finite_and_positive() {
        let golden = load_hydraulics_golden();
        for (i, row) in golden.darcy_weisbach.iter().enumerate() {
            assert!(
                row.reynolds.is_finite() && row.reynolds > 0.0,
                "row {i}: reynolds must be finite positive, got {}",
                row.reynolds
            );
            assert!(
                row.friction_factor.is_finite() && row.friction_factor > 0.0,
                "row {i}: friction_factor must be finite positive, got {}",
                row.friction_factor
            );
        }
    }

    /// Schema smoke test: each Manning full-pipe row has plausible values.
    #[test]
    fn manning_full_pipe_rows_are_finite_and_positive() {
        let golden = load_hydraulics_golden();
        for (i, row) in golden.manning_full_pipe.iter().enumerate() {
            assert!(
                row.velocity_m_s.is_finite() && row.velocity_m_s > 0.0,
                "row {i}: velocity must be finite positive, got {}",
                row.velocity_m_s
            );
            assert!(
                row.capacity_m3s.is_finite() && row.capacity_m3s > 0.0,
                "row {i}: capacity must be finite positive, got {}",
                row.capacity_m3s
            );
        }
    }
}
