//! oracle — Golden fixture loader for differential-oracle integration tests.
//!
//! This crate deserializes committed JSON fixtures (generated by the Python
//! `hydro_engine` oracle) and exposes typed helper functions for downstream
//! crates' integration tests.
//!
//! # Usage
//!
//! ```rust,ignore
//! use oracle::hydraulics::load_hydraulics_golden;
//!
//! let fixtures = load_hydraulics_golden();
//! for row in &fixtures.darcy_weisbach {
//!     // assert_abs_diff_eq!(rust_result, row.expected, epsilon = 1e-9);
//! }
//! ```
//!
//! # Fixture location
//!
//! Fixtures live in `tests/oracle/fixtures/` and are committed to the repository.
//! Regenerate them by running `python tests/oracle/gen/generate_hydraulics.py`
//! with the Python oracle engine on the PYTHONPATH.

use std::path::{Path, PathBuf};

use serde::de::DeserializeOwned;
use thiserror::Error;

pub mod hydraulics;
pub mod norms;
pub mod solvers;
pub mod terrain;

/// Errors produced by the fixture loader.
#[derive(Debug, Error)]
pub enum OracleError {
    #[error("fixture file not found: {path}")]
    FileNotFound { path: PathBuf },

    #[error("failed to read fixture {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("failed to deserialize fixture {path}: {source}")]
    Json {
        path: PathBuf,
        #[source]
        source: serde_json::Error,
    },
}

/// Return the absolute path to the `tests/oracle/fixtures/` directory.
///
/// Works from any working directory by anchoring relative to this file's
/// location at compile time via `CARGO_MANIFEST_DIR`.
pub fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

/// Load and deserialize a named fixture JSON file.
///
/// # Arguments
///
/// * `name` — filename without extension, e.g. `"hydraulics_golden"`.
///
/// # Errors
///
/// Returns `OracleError::FileNotFound` when the fixture is missing,
/// `OracleError::Io` on I/O failures, and `OracleError::Json` on
/// deserialization errors.
pub fn load_fixture<T: DeserializeOwned>(name: &str) -> Result<T, OracleError> {
    let path = fixtures_dir().join(format!("{name}.json"));
    if !path.exists() {
        return Err(OracleError::FileNotFound { path });
    }
    let bytes = std::fs::read(&path).map_err(|e| OracleError::Io {
        path: path.clone(),
        source: e,
    })?;
    serde_json::from_slice(&bytes).map_err(|e| OracleError::Json { path, source: e })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixtures_dir_exists() {
        let dir = fixtures_dir();
        assert!(
            dir.exists(),
            "fixtures directory must exist at: {}",
            dir.display()
        );
    }
}
