//! Typed structs and loaders for the norms smoke and violations golden fixtures.
//!
//! `norms_smoke.json` is generated by
//! `tests/oracle/gen/generate_norms_smoke.py` and committed to the repository.
//!
//! `norms_violations_golden.json` is generated by
//! `tests/oracle/gen/generate_norms_violations.py` and committed to the
//! repository.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::{load_fixture, OracleError};

// ── NormsSmoke ────────────────────────────────────────────────────────────────

/// Rule counts for one canonical norm profile, broken down by project type.
///
/// The outer key is the SCREAMING_SNAKE_CASE project type name
/// ("SEWER", "WATER_SUPPLY", …). The value is the number of rules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsSmokEntry {
    /// Canonical norm code (e.g. "CONAGUA_MX").
    pub code: String,
    /// Rule counts keyed by project type name (SCREAMING_SNAKE_CASE).
    pub rule_counts: HashMap<String, usize>,
}

/// Root fixture struct for `norms_smoke.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsSmoke {
    pub profiles: Vec<NormsSmokEntry>,
}

/// Load `norms_smoke.json` (panics in tests if missing/malformed).
pub fn load_norms_smoke() -> NormsSmoke {
    load_fixture::<NormsSmoke>("norms_smoke")
        .expect("norms_smoke.json must be present; regenerate with generate_norms_smoke.py")
}

/// Load `norms_smoke.json` as `Result` (non-panicking).
pub fn try_load_norms_smoke() -> Result<NormsSmoke, OracleError> {
    load_fixture::<NormsSmoke>("norms_smoke")
}

// ── NormsViolationsGolden ─────────────────────────────────────────────────────

/// A single network-level validation case.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsViolationsCase {
    /// Canonical norm code to load via NormRegistry::get.
    pub norm_code: String,
    /// Project type name (SCREAMING_SNAKE_CASE, matches Rust ProjectType variants).
    pub project_type: String,
    /// Description/label for this fixture case.
    pub label: String,
    /// The fixed network to validate (serialized PipeNetwork).
    pub network: NormsViolationsNetwork,
    /// Expected hard violation count (oracle ground truth).
    pub expected_hard_count: usize,
    /// Expected compliant flag (oracle ground truth).
    pub expected_compliant: bool,
}

/// A minimal serialized network for the violations fixture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsViolationsNetwork {
    pub name: String,
    pub nodes: Vec<NormsViolationsNode>,
    pub pipes: Vec<NormsViolationsPipe>,
}

/// A node entry in the violations fixture network.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsViolationsNode {
    pub id: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub node_type: String,
    #[serde(default)]
    pub metadata: HashMap<String, serde_json::Value>,
}

/// A pipe entry in the violations fixture network.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsViolationsPipe {
    pub id: String,
    pub start_node_id: String,
    pub end_node_id: String,
    pub length: f64,
    pub diameter: f64,
    pub slope: f64,
    pub roughness: f64,
    pub design_flow: f64,
    /// Explicit start invert elevation (m). When present, the Rust test uses
    /// this value directly. When absent, the test falls back to the historic
    /// default of 8.5 m (gives 1.5 m cover when node z = 10.0).
    #[serde(default)]
    pub start_invert: Option<f64>,
    #[serde(default)]
    pub metadata: HashMap<String, serde_json::Value>,
}

/// Root fixture struct for `norms_violations_golden.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormsViolationsGolden {
    pub cases: Vec<NormsViolationsCase>,
}

/// Load `norms_violations_golden.json` (panics in tests if missing/malformed).
pub fn load_norms_violations_golden() -> NormsViolationsGolden {
    load_fixture::<NormsViolationsGolden>("norms_violations_golden")
        .expect("norms_violations_golden.json must be present; regenerate with generate_norms_violations.py")
}

/// Load `norms_violations_golden.json` as `Result` (non-panicking).
pub fn try_load_norms_violations_golden() -> Result<NormsViolationsGolden, OracleError> {
    load_fixture::<NormsViolationsGolden>("norms_violations_golden")
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn norms_smoke_loads_and_has_15_profiles() {
        let smoke = load_norms_smoke();
        assert_eq!(
            smoke.profiles.len(),
            15,
            "expected exactly 15 canonical profiles, got {}",
            smoke.profiles.len()
        );
    }

    #[test]
    fn norms_smoke_all_profiles_have_6_project_types() {
        let smoke = load_norms_smoke();
        let expected_keys = [
            "SEWER",
            "WATER_SUPPLY",
            "CONVEYANCE",
            "DISTRIBUTION",
            "PUMP_STATION",
            "INTAKE",
        ];
        for entry in &smoke.profiles {
            for key in &expected_keys {
                assert!(
                    entry.rule_counts.contains_key(*key),
                    "profile {} missing rule_counts key '{}'",
                    entry.code,
                    key
                );
            }
        }
    }
}
