//! Typed structs and loaders for the hydro-solvers golden fixtures.
//!
//! `solvers_sewer_golden.json` is generated by
//! `tests/oracle/gen/generate_solvers_sewer.py` and committed to the repository.

use serde::{Deserialize, Serialize};

use crate::{load_fixture, OracleError};

// ── SewerSolver fixture structs ───────────────────────────────────────────────

/// Terrain parameters embedded in the sewer fixture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerTerrainParams {
    pub grid_res: f64,
    pub x_min: f64,
    pub x_max: f64,
    pub y_min: f64,
    pub y_max: f64,
    /// z = base_z + slope_x * x
    pub slope_x: f64,
    pub base_z: f64,
    /// All terrain points as [x, y, z] triples.
    pub points: Vec<[f64; 3]>,
}

/// Solver input parameters embedded in the sewer fixture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerSolverParams {
    pub outlet: [f64; 2],
    pub service_points: Vec<[f64; 2]>,
    pub flow_per_service: f64,
    pub material: String,
    pub grid_resolution: f64,
    pub num_alternatives: u32,
    pub route_variant: u32,
    pub slope_factor: f64,
    pub cover_factor: f64,
    pub diameter_offset: i32,
    pub manhole_spacing: Option<f64>,
}

/// One node in the oracle-built sewer network.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerNodeGolden {
    pub id: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    /// Node type string: "MANHOLE", "JUNCTION", "OUTLET", "SERVICE", "PUMP", etc.
    pub node_type: String,
    pub rim_elevation: f64,
    pub sump_elevation: f64,
}

/// One pipe in the oracle-built sewer network.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerPipeGolden {
    pub id: String,
    pub start_node_id: String,
    pub end_node_id: String,
    pub length: f64,
    pub diameter: f64,
    pub slope: f64,
    pub start_invert: f64,
    pub end_invert: f64,
    pub design_flow: f64,
    pub roughness: f64,
    pub bypassed_by_pump: bool,
}

/// Oracle score values.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerScoreGolden {
    pub total_cost: f64,
    pub total_length: f64,
    pub total_excavation: f64,
    pub norm_violations: i64,
    pub pump_count: i64,
}

/// Evaluate-only sub-fixture with details dict.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerEvaluateOnlyGolden {
    pub total_cost: f64,
    pub total_length: f64,
    pub total_excavation: f64,
    pub norm_violations: i64,
    pub pump_count: i64,
    /// Oracle details dict (pipe_count, node_count, avg_excavation).
    pub details: SewerDetailsGolden,
}

/// Oracle details dict fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerDetailsGolden {
    pub pipe_count: f64,
    pub node_count: f64,
    pub avg_excavation: f64,
}

/// Cost formula parameters for assertion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerCostFormula {
    pub w_length: f64,
    pub w_excavation: f64,
    pub w_violations: f64,
    pub expected_cost: f64,
}

/// Root fixture struct for `solvers_sewer_golden.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SewerGolden {
    pub schema_version: u32,
    pub fixture_name: String,
    pub description: String,
    /// Terrain reconstruction parameters.
    pub terrain: SewerTerrainParams,
    /// Solver input parameters used to produce this fixture.
    pub solver_params: SewerSolverParams,
    /// Expected node count.
    pub node_count: usize,
    /// Expected pipe count.
    pub pipe_count: usize,
    /// Expected total pipe length (m).
    pub total_length: f64,
    /// Oracle network nodes.
    pub nodes: Vec<SewerNodeGolden>,
    /// Oracle network pipes.
    pub pipes: Vec<SewerPipeGolden>,
    /// Primary solve() score.
    pub score: SewerScoreGolden,
    /// evaluate_only sub-fixture (independent evaluate() test).
    pub evaluate_only: SewerEvaluateOnlyGolden,
    /// Cost formula parameters.
    pub cost_formula: SewerCostFormula,
}

// ── Loaders ───────────────────────────────────────────────────────────────────

/// Load `solvers_sewer_golden.json` (panics in tests if missing/malformed).
pub fn load_sewer_golden() -> SewerGolden {
    load_fixture::<SewerGolden>("solvers_sewer_golden").expect(
        "solvers_sewer_golden.json must be present; regenerate with generate_solvers_sewer.py",
    )
}

/// Load `solvers_sewer_golden.json` as `Result` (non-panicking).
pub fn try_load_sewer_golden() -> Result<SewerGolden, OracleError> {
    load_fixture::<SewerGolden>("solvers_sewer_golden")
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sewer_golden_loads_and_has_correct_shape() {
        let f = load_sewer_golden();
        assert_eq!(f.schema_version, 1);
        assert!(f.node_count > 0, "must have nodes");
        assert!(f.pipe_count > 0, "must have pipes");
        assert_eq!(
            f.nodes.len(),
            f.node_count,
            "nodes array matches node_count"
        );
        assert_eq!(
            f.pipes.len(),
            f.pipe_count,
            "pipes array matches pipe_count"
        );
    }

    #[test]
    fn sewer_golden_cost_formula_is_consistent() {
        let f = load_sewer_golden();
        let cf = &f.cost_formula;
        let eo = &f.evaluate_only;
        let expected = cf.w_length * eo.total_length
            + cf.w_excavation * eo.total_excavation
            + cf.w_violations * eo.norm_violations as f64;
        assert!(
            (expected - cf.expected_cost).abs() < 1e-4,
            "cost formula inconsistent: computed={expected:.6} oracle={:.6}",
            cf.expected_cost
        );
    }

    #[test]
    fn sewer_golden_has_gravity_and_pump_pipes() {
        let f = load_sewer_golden();
        // Fixture has pump_count > 0 (some y-direction pipes need pumps on flat terrain)
        let pump_pipe_count = f.pipes.iter().filter(|p| p.bypassed_by_pump).count();
        let gravity_count = f.pipes.iter().filter(|p| !p.bypassed_by_pump).count();
        assert!(pump_pipe_count > 0, "fixture must have pump-bypassed pipes");
        assert!(gravity_count > 0, "fixture must have gravity pipes");
    }
}
