//! Typed structs and loaders for the terrain golden fixture.
//!
//! `terrain_golden.json` is generated by
//! `tests/oracle/gen/generate_terrain.py` and committed to the repository.

use serde::{Deserialize, Serialize};

use crate::{load_fixture, OracleError};

// ── On-sample query ────────────────────────────────────────────────────────

/// A single on-sample elevation query (point lies exactly on a grid node).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnSampleQuery {
    pub x: f64,
    pub y: f64,
    /// Ground-truth elevation (the exact DEM value at this grid node).
    pub expected_z: f64,
    /// Index into `TerrainGolden::points` that the KDTree should return.
    pub nearest_idx: usize,
    /// Oracle `elevation_at(x, y)` — should equal `expected_z` on-sample.
    pub elevation_at_z: f64,
}

// ── Off-grid query ─────────────────────────────────────────────────────────

/// A single off-grid elevation query (point does NOT lie on a grid node).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffGridQuery {
    pub x: f64,
    pub y: f64,
    /// Oracle `elevation_at(x, y)` — the Python RegularGridInterpolator result.
    pub oracle_z: f64,
}

// ── Dijkstra case ──────────────────────────────────────────────────────────

/// A single Dijkstra path query from oracle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DijkstraCase {
    pub source_id: String,
    pub target_id: String,
    /// Ordered list of node IDs in the shortest path.
    pub path: Vec<String>,
    /// Total weighted cost of the shortest path.
    pub total_weight: f64,
}

// ── Nearest-node case ──────────────────────────────────────────────────────

/// A single nearest-node query from oracle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NearestNodeCase {
    pub query_x: f64,
    pub query_y: f64,
    /// Expected node ID returned by `nearest_node(x, y)`.
    pub expected_node_id: String,
}

// ── Graph fixture ──────────────────────────────────────────────────────────

/// The TerrainGraph structural and algorithmic oracle fixture.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphFixture {
    /// Grid resolution used to build the TerrainGraph.
    pub resolution: f64,
    /// Expected number of nodes.
    pub node_count: usize,
    /// Expected number of edges.
    pub edge_count: usize,
    /// Dijkstra path queries to assert against.
    pub dijkstra_cases: Vec<DijkstraCase>,
    /// Nearest-node queries to assert against.
    pub nearest_node_cases: Vec<NearestNodeCase>,
}

// ── Root fixture ───────────────────────────────────────────────────────────

/// Root fixture struct for `terrain_golden.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerrainGolden {
    pub schema_version: u32,
    pub fixture_name: String,
    pub grid_res: f64,
    pub x_min: f64,
    pub x_max: f64,
    pub y_min: f64,
    pub y_max: f64,
    /// All DEM points as `[x, y, z]` triples.
    pub points: Vec<[f64; 3]>,
    /// On-sample elevation queries.
    pub on_sample_queries: Vec<OnSampleQuery>,
    /// Off-grid interior elevation queries.
    pub off_grid_queries: Vec<OffGridQuery>,
    /// Oracle-vs-oracle p95 absolute error (always 0; documents the gate).
    pub off_grid_p95_abs_error: f64,
    /// Resolution used for `build_grid` on TerrainModel.
    pub build_grid_res: f64,
    /// TerrainGraph structural and algorithmic fixture.
    pub graph_fixture: GraphFixture,
}

// ── Loaders ────────────────────────────────────────────────────────────────

/// Load `terrain_golden.json` (panics in tests if missing/malformed).
pub fn load_terrain_golden() -> TerrainGolden {
    load_fixture::<TerrainGolden>("terrain_golden")
        .expect("terrain_golden.json must be present; regenerate with generate_terrain.py")
}

/// Load `terrain_golden.json` as `Result` (non-panicking).
pub fn try_load_terrain_golden() -> Result<TerrainGolden, OracleError> {
    load_fixture::<TerrainGolden>("terrain_golden")
}

// ── Irregular-scatter fixture ──────────────────────────────────────────────

/// A single off-grid query from the irregular-scatter oracle.
///
/// `oracle_z` is Python's `TerrainModel.elevation_at(x, y)` after
/// `build_grid` was called on the *same* irregular scatter points.
/// The Python side uses scipy.griddata Delaunay-linear; the Rust side
/// uses IDW-bilinear (ADR-5). This struct captures the ground-truth
/// expected by the spec R-04 statistical gate (p95 < 0.1 m).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IrregularOffGridQuery {
    pub x: f64,
    pub y: f64,
    /// Oracle elevation from scipy Delaunay-linear + RegularGridInterpolator.
    pub oracle_z: f64,
}

/// Root fixture for `terrain_irregular_golden.json`.
///
/// Generated by the `irregular_scatter` section of `generate_terrain.py`
/// using `np.random.RandomState(seed=7777)` over the same sin/cos surface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IrregularTerrainGolden {
    pub schema_version: u32,
    pub fixture_name: String,
    /// Build-grid resolution (meters).
    pub build_grid_res: f64,
    /// Domain bounds (x_min, x_max, y_min, y_max).
    pub x_min: f64,
    pub x_max: f64,
    pub y_min: f64,
    pub y_max: f64,
    /// Fixed RNG seed used to generate scatter points.
    pub scatter_seed: u64,
    /// Number of scatter (input) points.
    pub n_scatter: usize,
    /// All scatter points as `[x, y, z]` triples (the same points fed
    /// to both the Python oracle and the Rust TerrainModel).
    pub scatter_points: Vec<[f64; 3]>,
    /// Off-grid query points with scipy oracle elevations.
    pub off_grid_queries: Vec<IrregularOffGridQuery>,
    /// Python-measured p95 abs error (oracle vs oracle = 0; for documentation).
    pub off_grid_p95_oracle_vs_oracle: f64,
}

// ── Loaders for irregular fixture ─────────────────────────────────────────

/// Load `terrain_irregular_golden.json` (panics in tests if missing/malformed).
pub fn load_irregular_terrain_golden() -> IrregularTerrainGolden {
    load_fixture::<IrregularTerrainGolden>("terrain_irregular_golden").expect(
        "terrain_irregular_golden.json must be present; regenerate with generate_terrain.py",
    )
}

/// Load `terrain_irregular_golden.json` as `Result` (non-panicking).
pub fn try_load_irregular_terrain_golden() -> Result<IrregularTerrainGolden, OracleError> {
    load_fixture::<IrregularTerrainGolden>("terrain_irregular_golden")
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn terrain_golden_loads_and_has_correct_shape() {
        let f = load_terrain_golden();
        assert_eq!(f.schema_version, 1);
        assert_eq!(
            f.points.len(),
            10_000,
            "expected 100x100=10000 DEM points, got {}",
            f.points.len()
        );
        assert_eq!(
            f.on_sample_queries.len(),
            50,
            "expected 50 on-sample queries"
        );
        assert_eq!(
            f.off_grid_queries.len(),
            200,
            "expected 200 off-grid queries"
        );
    }

    #[test]
    fn terrain_golden_graph_fixture_has_expected_counts() {
        let f = load_terrain_golden();
        let gf = &f.graph_fixture;
        // 20m grid over 0..990 terrain: arange(0, 990+20, 20) = 0,20,...,980 → 50 values
        // 50 x 50 = 2500... wait, terrain bounds are 0..990 for both axes
        // xs = arange(0, 990+20, 20) = 0,20,40,...,980 → 50 values
        // ys = arange(0, 990+20, 20) = 50 values
        // nodes = 50*50 = 2500? But generator says 2601
        // Let's check: arange(0, 990+20, 20) with step 20:
        //   0, 20, 40, ..., up to but not exceeding 990+20=1010
        //   max value <= 1010: 0, 20, ..., 1000 → 51 values
        // 51 x 51 = 2601 nodes ✓
        assert_eq!(
            gf.node_count, 2601,
            "expected 2601 nodes (51x51 grid at res=20m over 0..990)"
        );
        assert_eq!(
            gf.edge_count, 5100,
            "expected 5100 edges (4-neighbor: 51*50 + 50*51 = 2550 + 2550 = 5100)"
        );
        assert!(!gf.dijkstra_cases.is_empty(), "must have dijkstra cases");
        assert_eq!(
            gf.nearest_node_cases.len(),
            5,
            "must have 5 nearest-node cases"
        );
    }

    #[test]
    fn irregular_terrain_golden_loads_and_has_correct_shape() {
        let f = load_irregular_terrain_golden();
        assert_eq!(f.schema_version, 1);
        assert!(
            f.scatter_points.len() >= 100,
            "expected at least 100 scatter points, got {}",
            f.scatter_points.len()
        );
        assert!(
            f.off_grid_queries.len() >= 50,
            "expected at least 50 off-grid queries, got {}",
            f.off_grid_queries.len()
        );
        assert_eq!(
            f.scatter_points.len(),
            f.n_scatter,
            "n_scatter field must match actual points count"
        );
    }
}
